name: 'Execute tests'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    name: Run local unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Cache all .gradle folders in project
        uses: actions/cache@v4
        with:
          path: |
            **/.gradle
          key: gradle-test-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', '**/settings.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-test-${{ runner.os }}-
  
      - name: Cache all build folders in project
        uses: actions/cache@v4
        with:
          path: |
            **/build
          key: build-test-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            build-test-${{ runner.os }}-
      - name: Local unit tests with Gradle
        run: ./gradlew testFDroidDebugUnitTest
      - name: Upload tests results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: ./**/testFDroidDebugUnitTest/TEST-*.xml
