name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build and Upload Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: set NDK
      shell: bash
      run: |
        set -x
        echo "ANDROID_NDK=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

    - name: Restore keystore
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" > smartautoclicker.jks.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch smartautoclicker.jks.asc > smartautoclicker/smartautoclicker.jks

    - name: Build with Gradle
      run: |
        ./gradlew --info \
          -PsigningStorePassword="${{ secrets.SIGNING_STORE_PASSWORD }}" \
          -PsigningKeyAlias="${{ secrets.SIGNING_KEY_ALIAS }}" \
          -PsigningKeyPassword="${{ secrets.SIGNING_KEY_PASSWORD }}" \
          assembleFDroidRelease bundleFDroidRelease

    - name: Rename APK with tag or branch
      run: |
        REF_NAME="${GITHUB_REF##*/}"
        mkdir release-apk
        cp smartautoclicker/build/outputs/apk/fDroid/release/*.apk "release-apk/click-fork-${REF_NAME}.apk"

    - name: Upload APK to GitHub Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        files: release-apk/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: click-fork-release
        path: release-apk/*.apk
