name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build and Upload Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Restore keystore
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" > smartautoclicker.jks.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch smartautoclicker.jks.asc > smartautoclicker/smartautoclicker.jks

    - name: Build with Gradle
      run: |
        ./gradlew \
          -PsigningStorePassword="${{ secrets.SIGNING_STORE_PASSWORD }}" \
          -PsigningKeyAlias="${{ secrets.SIGNING_KEY_ALIAS }}" \
          -PsigningKeyPassword="${{ secrets.SIGNING_KEY_PASSWORD }}" \
          assembleFDroidRelease bundleFDroidRelease

    - name: Rename APK with tag
      run: |
        TAG_NAME="${GITHUB_REF##*/}"
        mkdir release-apk
        cp smartautoclicker/build/outputs/apk/fdroid/release/*.apk "release-apk/click-fork-${TAG_NAME}.apk"

    - name: Upload APK to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: release-apk/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
